const empresas = require('../modules/empresas/network')
const loginEmpresas = require('../modules/empresas/login')
const servicios = require('../modules/servicios/network')
const areas = require('../modules/areas/network')
const planes = require('../modules/planes/network')
const cargos = require('../modules/cargos/network')
const personal = require('../modules/personal/network')
const loginPersonal = require('../modules/personal/login')
const directiva = require('../modules/directiva/network')
const contactos = require('../modules/contactos/network')
const proveedores = require('../modules/proveedores/network')
const loginProveedores = require('../modules/proveedores/login')
const recursos = require('../modules/recursos/network')
const tickets = require('../modules/tickets/network')

const routes = function (server) {
    server.use('/empresas', empresas)
    server.use('/loginEmpresas', loginEmpresas)
    server.use('/servicios', servicios)
    server.use('/areas', areas)
    server.use('/planes', planes)
    server.use('/cargos', cargos)
    server.use('/personal', personal)
    server.use('/loginPersonal', loginPersonal)
    server.use('/directiva', directiva)
    server.use('/contactos', contactos)
    server.use('/proveedores', proveedores)
    server.use('/loginProveedores', loginProveedores)
    server.use('/recursos', recursos)
    server.use('/tickets', tickets)
    server.use('/tickets/servicios', tickets)
    server.use('/tickets/proyectos', tickets)
    server.use('/tickets/reportes', tickets)
    server.use('/tickets/consultas', tickets)
}

module.exports = routes